services:
  install:
    container_name: install
    restart: always
    build:
      dockerfile: Dockerfile
    volumes:
      - ../install-mods-store:/app/store
    ports:
      - 9108:3000
    environment:
      - GITHUB_API_TOKEN
